### PR TITLE
Update Okta Verify recipe to disable bundle relocation.

### PR DESCRIPTION
**Pull request by ccaviness**
To do this, modify the `PackageInfo` in the unpacked flat pkg and remove the `<relocate>` element. Then, re-pack the pkg.

This uses the `com.github.ccaviness.processors/XMLModifier` processor to make the change.

### CODE REVIEW

**Comment by ccaviness** [comment]
My IDE also did a bunch of automatic formatting, which re-arranged some things. If you'd like a PR without the formatting changes I can do that instead.

**Comment by nstrauss** [comment]
@ccaviness I've run into this myself and realize it's a problem. However, I would prefer not to modify the package as is from the vendor, which in turn breaks code signing. Please open an issue with Okta support instead and I will file an issue internally to fix the package build. 

Appreciate the work here, but it goes against the expectations most people have with widely used community recipes. IMO recipes should do as little processing as possible. Feel free to fork my recipe and publish your own. I only ask it be renamed and the description updated to explain how it diverges.

**Comment by ccaviness** [comment]
I've reported this to Okta already in https://ideas.okta.com/app/#/case/206761

Thanks! I'll work around this internally.

**Comment by nstrauss** [comment]
I currently work at Okta so hopefully I can get some traction internally. No promises of course.

**Pull request closed without merging**
